name: Backend Docker CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Build Backend Docker Image
        run: |
          docker build \
            -f Dockerfile.backend \
            -t shestay-backend .